server:
  port: 8765

spring:
  application:
    name: edge-service

security:
  oauth2:
#    client:
#      accessTokenUri: http://localhost:9999/oauth/token
#      userAuthorizationUri: http://localhost:9999/oauth/authorize
#      clientId: reader
#      clientSecret: readerSecret
#      scope: read
    resource:
      jwt:
        key-value: 123

zuul:
  sensitive-headers: Cookie,Set-Cookie
  prefix: /api
  routes:
    food-catalog-service:
      path: /food-client-service/**
      serviceId: food-client-service
    oauth-service:
      path: /oauth-service/**
      serviceId: oauth-service